### ISSUE TITLE
Lack of navigation to a page

### ISSUE THREAD

**Issue by SuTran** [PSPDFKit/react-native#93] opened 2018-07-17 06:17 UTC
### Description:
We've already bought a license of PSPDF to integrate with our app. Not sure you have a dedicated place to support customer, better to create issue at the moment.
### Acceptance Criteria:
- [ ] Page can pass to `PSPDFKit.present` or `PSPDFKitView` when they first initialized. When the PDF file shown up, it should navigate to that page
- [ ] When PDF file already shown up, should have the API to navigate to specific page
- [ ] Above configurations should be mentioned in https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html

**Comment by steipete** [comment] 2018-07-17 07:40
Hi! We are going to implement this in https://github.com/PSPDFKit/react-native/issues/87

I appreciate you writing the issue report here right away and even using our Acceptance Criteria format - really great!

For planning purposes, please reach out for future issues via https://pspdfkit.com/support/request/ - we usually take over issue writing both on the private and public repos, so there's less chance of duplicates. Thanks!

**Comment by radazzouz** [comment] 2018-07-17 17:05
@SuTran I am closing this issue as a duplicate of #87

**Closed by radazzouz** 2018-07-17 17:05 UTC
