### ISSUE TITLE
Customizing the Toolbar in React-Native/Windows

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#158] opened 2019-01-11 18:41 UTC
Hey, 
after an eternity going through the repository and documentation I thought it may be best to ask directly. 
I'm currently working on a Project for a client, a Windows application, and need to implement the pspdfkit with customized toolbar. But I am working in JavaScript and don't know much about objective-c.
Is it even possible to do so by passing the right props to the PSPDFKitView? 
And if it's not possible by simply passing props, how can I customize it just using react-native for windows?

**Comment by steipete** [comment] 2019-01-11 19:45
Hi! Just checking in, while we estimate a timeline for the feature you ask for, are you already in contact with our sales team? If so, can you send us an email to sales@pspdfkit.com with this issue URL? Thanks!

**Comment by steipete** [comment] 2019-01-15 15:55
I've checked with the team, this is not currently possible, but we'll consider this as a future wrapper extension. Thanks for the suggestion!

**Comment by leoek** [comment] 2019-01-26 16:09
@steipete 
Hi, we are already in contact with your sales team and will email to sales@pspdfkit.com about this. Do you have a timeline for this feature yet?

**Comment by nickwinder** [comment] 2019-01-28 15:36
@leoek @Elmatoss 
I'll look into extending the wrapper to support toolbar customization shortly, and I will report back next week with any updates and advancements.

**Comment by nickwinder** [comment] 2019-02-05 20:06
@leoek I've made advancements in https://github.com/PSPDFKit/react-native/pull/165 and this adds the ability to customize the toolbar. I've sent an email with details on how to use this PR for development until an official release can be supported next week. Thanks

**Comment by leoek** [comment] 2019-02-07 17:20
@nickwinder I can confirm that I can customize the toolbar with the version from #165 🎉 

However the error handling seems to be a little of at this point. I sometimes get the following error:

```
System.Exception
  HResult=0x80131500
  Message=Exception while trying to SetToolbarItemsInWebAsync: Instance is undefined
  Source=PSPDFKit
  StackTrace:
   at PSPDFKit.Internal.Json.IfErrorThrow(String operationName, String resultString)
   at PSPDFKit.Internal.Web.<SetToolbarItemsAsync>d__41.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PSPDFKit.UI.Controller.<SetToolbarItemsInWebAsync>d__97.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PSPDFKit.UI.Controller.<SetToolbarItemsAsyncInternal>d__42.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ReactNativePSPDFKit.PSPDFKitViewManger.<ReceiveCommand>d__16.MoveNext() in C:\projects\insession\node_modules\react-native-pspdfkit\windows\ReactNativePSPDFKit\ReactNativePSPDFKit\PSPDFKitViewManager.cs:line 114

Inner Exception 1:
Exception: Instance is undefined
```

I think the best solution would be to handle these errors inside pspdfkit and let the wrapper return a promise for setToolbarItems. Currently the error results in a crash of the whole app.

The code I am using to modify the toolbar right now (just for reference): 
```
customizeToolbar = (pdfView = this.pdfView) => {
    const { toolbarItemsBlacklist } = this.props;
    if (!pdfView) return false;
    const currentToolbarItemsPromise = pdfView.getToolbarItems();
    currentToolbarItemsPromise.then((currentToolbarItems = []) => {
      const toolbarItems = currentToolbarItems.filter(item => !toolbarItemsBlacklist.includes(item.type));
      //console.log(pdfView)
      pdfView && pdfView.setToolbarItems(toolbarItems);

...
```

**Comment by leoek** [comment] 2019-02-07 17:32
Ah and I am not sure whether you have encountered this issue before, but yarn seems to retrieve older versions than pinned in the `yarn.lock` if there is a branch or tag referenced in the `package.json` and there is a version on master which has the same version string in its package.json as the one on the referenced branch or tag.

Example:
I run `yarn add github:PSPDFKit/react-native-pspdfkit#nick/uwp/support-custom-toolbar` 
--> my package.json and lockfile change accordingly and reference 1.23.0, yarn installs the latest version from `nick/uwp/support-custom-toolbar`
--> everything as expected until this point
A colleague runs `yarn` to fetch the new dependencies.
--> he gets another version which has 1.23.0 in its package.json as well, but is not  the latest from  `nick/uwp/support-custom-toolbar`

**Comment by nickwinder** [comment] 2019-02-07 18:05
Thanks! I'll take the advice on board and look to improve the API. 

`Instance is undefined` Tells me that a `PDFView` has not been setup/shown yet. I'll have to look into the reason why it'd be possible to try and set the toolbar up before the `PDFView` is ready. 

As for the issue you see with yarn, I'm not too surprised although I've not knowingly encountered it before. I've found many weird situations with yarn, and npm. Yarn seemed more reproducible in the end but there are still points where nuking `node_modules` and cache is required.

**Comment by leoek** [comment] 2019-02-07 19:55
Hi, the reason why I want to setup the toolbars as early as possible is that we don't want the user to see options for very short amount of time which will disappear later.

I thought I would be save if I waited until the reference in this.pdfView was ready. That's why I included this line: `if (!pdfView) return false;`

**Comment by leoek** [comment] 2019-02-07 19:58
About the yarn issue: These were the changes which fixed it for me: https://github.com/leoek/react-native-pspdfkit/commit/eb7ab3515a29fa17fe675a8f81fb8b8608d2864c

**Comment by nickwinder** [comment] 2019-02-11 14:57
Hey @leoek,

I've been testing with https://github.com/PSPDFKit/react-native/pull/165. I've taken your advice and wrapped the throw and passed it on via the promise. I will follow up with promise throws for the other setter methods. 

I've been unable to reproduce your specific issue though. I've tried calling the method early and late. The SDK should be accounting for situations where the instance is not available for usage yet. These values are cached and written upon load time. We would only have to check that your local react `pdfView` is available.

```
class PdfViewToolbarCustomizationScreen extends Component<{}> {
  constructor(props) {
    super(props);
    this.toolbarItemsBlacklist = [
      "ink"
    ];
    this.customizeToolbar();
  }

  render() {
    return (
      <View style={styles.page}>
        <PSPDFKitView
          ref="pdfView"
          style={styles.pdfView}
          // The default file to open.
          document="ms-appx:///Assets/pdf/annualReport.pdf"
        />
        <View style={styles.footer}>
          <View style={styles.button}>
            <Button onPress={() => this.customizeToolbar()} title="Customize" />
          </View>
        </View>
      </View>
    );
  }

  customizeToolbar = (pdfView = this.refs.pdfView) => {
    if (!pdfView) {
      return false;
    }
    const currentToolbarItemsPromise = pdfView.getToolbarItems();
    currentToolbarItemsPromise.then((currentToolbarItems = []) => {
      const toolbarItems = currentToolbarItems.filter(item => !this.toolbarItemsBlacklist.includes(item.type));
      //console.log(pdfView)
      pdfView && pdfView.setToolbarItems(toolbarItems).catch((error) => { alert(error.Message); });
    });
  };
}
```

This is the example component I used to test the behavior. I tried to mimic your code where possible. More information would be great. Thanks.

**Comment by leoek** [comment] 2019-02-13 19:10
Do I need to reference a new nightly sdk, if I want to test you new changes?

I believe the error does not appear, if the you have a fixed document (`document="ms-appx:///Assets/pdf/annualReport.pdf"`).

The Error seems to be more likely, if the call to `addAnnotaiton` or `setToolbarItems` happens shortly, after changing the pdf with `PSPDFKit.Present`.

It would really help, if `PSPDFKit.Present` would return a promise to avoid these errors, as described in #170

**Comment by nickwinder** [comment] 2019-02-14 16:38
Thanks for the information. You can use the same nightly binary you have already downloaded.

I will look into https://github.com/PSPDFKit/react-native/issues/170 in which the promise can monitor the `DocumentReady` callback. This may well help the issue.

**Comment by leoek** [comment] 2019-02-14 18:33
Thanks! I have upgraded our react-native-wrapper to your latest version and can confirm, that setToolbarItems will still fail, if it was called shortly after PSPDFKit.Present, but we can handle it now, with the promise which is returned by setToolbarItems.

**Comment by nickwinder** [comment] 2019-02-15 09:02
Great, I'm glad we're getting closer to a better solution. I'll let you know when I've made changes to `Present` and I  can work on closing this issue. 

FYI: We have just released PSPDFKit for Windows 1.10.1. So you can now use this instead of the nightly. Please ensure you fully uninstall the nightly `1.10.1`. I will be updating `react-native-pspdfkit` with official support today.

**Comment by nickwinder** [comment] 2019-02-22 07:39
@leoek I added the promise to the `Present` API in order to retrieve open and error information. 
Before merging https://github.com/PSPDFKit/react-native/pull/172 I'd like to ensure that API works how you'd expect.

**Comment by leoek** [comment] 2019-02-22 23:46
Thanks! Will test on monday.

**Comment by nickwinder** [comment] 2019-03-07 05:32
@leoek How did the test go?

**Comment by nickwinder** [comment] 2019-03-08 12:16
@leoek This is now merged. If you have any further suggestions or question in this area please open a new issue. Thanks.

**Closed** 2019-03-08 12:15 UTC
Labels: help wanted, question, windows

**Comment by leoek** [comment] 2019-03-11 13:21
@nickwinder Sorry, I just forgot about getting back to you about #165 

It seems to work fine for me on windows. However it seems like I cannot use the same function on ios.

**Comment by nickwinder** [comment] 2019-03-11 13:37
@leoek That's ok. 

The Windows toolbar and UI is inherently different from Android/iOS. Therefore we have to take a different approach here along with some other features. We've attempted to align the API where possible. I apologize for the inconvenience here and be sure to reach out if you need any help in this area. 

See https://github.com/PSPDFKit/react-native/blob/master/README.md#menu-item-mapping for iOS implementation and https://github.com/PSPDFKit/react-native/blob/master/README.md#menu-item-mapping-1 for Android implementation.

**Comment by leoek** [comment] 2019-03-11 14:53
Yes that is what I am currently doing for ios. I hoped that I could use the same code. Thanks for the links though!
