### ISSUE TITLE
[IOS] documentLabelEnabled does not work any more

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#220] opened 2019-04-30 13:53 UTC
# Details

If the configuraiton options
```javascript
documentLabelEnabled: false,
allowToolbarTitleChange: false,
```
are set, the toolbar shouldn't contain the filename as title. However in version 1.23.7 the configuration seems to have no effect.

This worked in version 1.23.3

# Acceptance Criteria

- [ ] The filename is not shown in the toolbar if `documentLabelEnabled` is set to false.

**Comment by radazzouz** [comment] 2019-04-30 14:46
@leoek,

I was unable to reproduce this behavior in our sample catalog example.

I modified the our "Configured Controller" and "PDF View Component" examples [here](https://github.com/PSPDFKit/react-native/blob/master/samples/Catalog/Catalog.ios.js#L70), to test both the Native Module and the View Component and, like so:

```js
  {
    key: "item3",
    name: "Configured Controller",
    description:
      "You can configure the controller with dictionary representation of the PSPDFConfiguration object.",
    action: () => {
      PSPDFKit.present("PDFs/Annual Report.pdf", {
        pageScrollDirection: "horizontal",
        backgroundColor: processColor("white"),
        showThumbnailBar: "scrollable",
        pageTransition: "scrollContinuous",
        documentLabelEnabled: false,
        allowToolbarTitleChange: false, 
        inlineSearch: true
      });
    }
  },
  {
    key: "item4",
    name: "PDF View Component",
    description:
      "Show how to use the PSPDFKitView component with NavigatorIOS.",
    action: component => {
      const nextRoute = {
        component: PSPDFKitView,
        passProps: {
          document: "PDFs/Annual Report.pdf",
          configuration: {
            useParentNavigationBar: true,
            documentLabelEnabled: false,
            allowToolbarTitleChange: false, 
          },
          style: { flex: 1 }
        }
      };
      component.props.navigator.push(nextRoute);
    }
  },
```

In my tests, I used version 1.23.8 and PSPDFKit 8.3.0 for iOS, please upgrade both our wrapper and PSPDFKit for iOS, and let me know if this happens still in our Catalog sample project.

I'm closing this issue, but feel free to comment on it or reopen it with additional steps to reproduce.

Thank you!

**Comment by leoek** [comment] 2019-05-06 15:44
@radazzouz please reopen the issue. I have created a reproducible demo for you.

**Steps to reproduce**

General:

1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. checkout the branch `reproduce-issue-220`
2. install dependencies with yarn: `yarn`
3. copy the pspdfkit lib (demo version) into ios/PSPDFKit (we only track the VERSION file in the git repository)
4. open the xcode project in xcode and run the app on an ipad

Issue specific:

5. Click on "Go To PdfScreen"
6. Click on "Back" (Top left corner)
7. Click on "Go To PdfScreen"

--> The filename is shown as documentlabel

Expected: There is no documentlabel shown.

**Comment by radazzouz** [comment] 2019-05-06 19:10
Thanks for the additional details, @leoek!

I was able to reproduce this behaviour on my side. In my tests, I used PSPDFKit for iOS 8.3.1 and version 1.23.9 of our wrapper.

`documentLabelEnabled` controls the overlay label with the document title.

<img width="916" alt="Screen Shot 2019-05-06 at 2 50 35 PM" src="https://user-images.githubusercontent.com/7443038/57247666-6eaa0500-700e-11e9-89f6-95631c05e24a.png">

In your sample project, this is never shown. So this works as expected.

So what you are seeing displayed, is the document title in the navigation bar the second time you open the PDF. The first time you open the document, the document is not loaded yet, so the title is not set (it is nil). On subsequent loads, the document's title is already loaded and we display its title. We do this because you are not using the parent navigation bar (the default value for `useParentNavigationBar` is false). See https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html#/c:objc(cs)PSPDFConfiguration(py)useParentNavigationBar and https://github.com/PSPDFKit/react-native/blob/992c55f1436630669d5123d75fbf472e5fbc6416/index.js#L329-L330

Your sample project is quite complex and I was unable to fully understand your navigation stack. So I can't offer a workaround in React Native Javascript. 

The easiest way to workaround this, would be in Objective-C, by setting your `PSPDFViewController's` title to nil in https://github.com/PSPDFKit/react-native/blob/992c55f1436630669d5123d75fbf472e5fbc6416/ios/RCTPSPDFKit/RCTPSPDFKitViewManager.m#L25-L35 

The implementation would look like this:

```objc
RCT_CUSTOM_VIEW_PROPERTY(document, pdfController.document, RCTPSPDFKitView) {
  if (json) {
    view.pdfController.document = [RCTConvert PSPDFDocument:json];
    view.pdfController.document.delegate = (id<PSPDFDocumentDelegate>)view;
    view.pdfController.title = nil;

    // The author name may be set before the document exists. We set it again here when the document exists.
    if (view.annotationAuthorName) {
      view.pdfController.document.defaultAnnotationUsername = view.annotationAuthorName;
    }
  }
}
```

Let me know if this helps you.

**Comment by leoek** [comment] 2019-05-07 09:28
@radazzouz 

**Regarding our demo application**

> Your sample project is quite complex and I was unable to fully understand your navigation stack. So I can't offer a workaround in React Native Javascript.

The PdfView Component needs many abstractions to be usable on all platforms because of different apis between windows and ios/android. Also some of the code is just there to avoid timing issues and crashes we were experiencing when using the methods from the wrapper directly. Also we need to keep track of the state the PdfView is in/was in because it is not reset if the component is unmounted and mounted again (at least on windows). 

I know that it isn't optimal to have the windows complexity and code to reproduce other issues in there. However we can't build a new demo application for every issue we encounter. (Currently PdfView.js can be copied mostly from our app and all the rest of the implementation around it is there to mimic situations which can happen for us in real world usage)

**About this specific Issue**

So there is no way to remove or change the label with the filename ("7_0 in this case) without forking the react-native-wrapper?

<img width="880" alt="Screenshot 2019-05-07 at 11 09 49" src="https://user-images.githubusercontent.com/9424038/57287870-aec5c200-70b8-11e9-83ce-94db953165a1.png">

**Comment by radazzouz** [comment] 2019-05-07 12:04
> So there is no way to remove or change the label with the filename ("7_0 in this case) without forking the react-native-wrapper?

[...]

> This: https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html#/c:objc(cs)PSPDFConfiguration(py)allowToolbarTitleChange sounded like it would prevent the title from being displayed..

Here are a few solutions that you can adopt to work around this:

1. Set `documentLabelEnabled` to false and `allowToolbarTitleChange` to true, the document title (not the file name) will be shown:

<img width="916" alt="Screen Shot 2019-05-07 at 7 56 21 AM" src="https://user-images.githubusercontent.com/7443038/57297472-ab710d00-709d-11e9-9655-e16a317e36c1.png">

2. If you don't want to show the document's title in the navigation bar, consider using a navigation setup that doesn't use the blue bar on top. Consider using a setup where `useParentNavigationBar` could be set to false.

3. If you want to use the existing navigation setup, the easiest solution would be to do it in Objective-C (https://github.com/PSPDFKit/react-native/issues/220#issuecomment-489739159), as we don't have JavaScript APIs that directly access the `PSPDFViewController`'s.

**Comment by radazzouz** [comment] 2019-05-21 13:33
I am closing this issue, as it isn't a wrapper-related issue.

Thanks again!

**Closed by radazzouz** 2019-05-21 13:33 UTC
Labels: bug, iOS

**Comment by leoek** [comment] 2019-06-06 15:43
@radazzouz It would be great if this could be adressed with #233 as well. We are currently setting the title to `nil` as suggested, but it would be much better if we could supply a string from js to display there.

**Comment by radazzouz** [comment] 2019-06-06 19:09
@leoek Can you please create a new issue with all the details to make sure that this request is not lost?

Thank you!
