### ISSUE TITLE
[UWP] Build is failing:  error MSB4064: The "PlatformXmlDir" parameter is not supported by the "CompileXa ml" task.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#161] opened 2019-01-19 23:32 UTC
## Full Error Message: 
```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(387,13): error MSB4064: The "PlatformXmlDir" parameter is not supported by the "CompileXa
ml" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\projects\react-native-pspdfkit-demo\node_modules\react-native-pspdfkit\windows\ReactNativePSPDFKi
t\ReactNativePSPDFKit\ReactNativePSPDFKit.csproj]
C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(353,5): error MSB4063: The "CompileXaml" task could not be initialized with its input par
ameters.  [C:\projects\react-native-pspdfkit-demo\node_modules\react-native-pspdfkit\windows\ReactNativePSPDFKit\ReactNativePSPDFKit\ReactNativePSPDFKit.csproj]
Build failed with message Error: Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" "C:/projects/react-native-pspdfkit-demo/windows/pspdfkitdemo.sln" /clp:NoSummary;NoItemAndPropertyList;Verbosity=quiet /nologo /p:Configuration=Debug /p:Platform=x86 /p:AppxBundle=Never /p:PlatformToolset=v141 /p:VisualStudioVersion=15.0. Check your build configuration.
```

## Steps to Reproduce
I have prepared a reproducable demo in [this repository.](https://github.com/leoek/react-native-pspdfkit-demo)

1. clone the repository and make sure you have the required windows sdks installed
2. insert license in windows/pspdfkitdemo/App.xaml 
3. run `yarn` (from powershell in the repos directory)
4. If necessary, open the project in visual studio, right click on the solution and select `restore nuget packages`
5. run `react-native run-windows` (from powershell in the repos directory)

**Comment by leoek** [comment] 2019-01-19 23:53
@nickwinder I added you to the private linked github repository with the demo. If I should invite anyone else, please comment here. 

If needed I can open the repository after a second review for sensitive information.

**Comment by nickwinder** [comment] 2019-01-19 23:58
Thanks for the detailed report @leoek. I'll look into the issue and get back to you.

**Comment by nickwinder** [comment] 2019-01-21 13:48
@leoek 
I've managed to have a look at your repository this morning. There seems to be a dependency on `react-native": "0.57.2"` and thus `react-native-windows": "0.57.0-rc.0"`. We have not fully tested the PSPDFKit react-native wrapper on these versions yet. In addition to this, I had to downgrade `react-native-fs`, I tested with `"react-native-fs": "2.10.14",`, but I'd suggest you find the correct version for yourself. 

I found that I could compile your project with the following changes.

```
"react-native": "0.55.4",
"react-native-fs": "2.10.14",
"react-native-windows": "0.55.0-rc.0",
```

Or as an alternative, you can reproduce a working setup by following the steps laid out in https://github.com/PSPDFKit/react-native#getting-started-2

On a side note, the following files were not committed into https://github.com/leoek/react-native-pspdfkit-demo which compilation of assets issues.
`windows\pspdfkitdemo\Assets\LockScreenLogo.scale-200.png`
`windows\pspdfkitdemo\Assets\pdfs\app-konzept.pdf`

After the above was working react-native had some errors with the javascript, but I believe that is a further issue for you to explore.

Let me know how this goes. 
Thanks again.

**Comment by leoek** [comment] 2019-01-22 10:43
@nickwinder 
Could you look into supporting RN 0.57? I don't want to downgrade to 0.55, because there were many changes introduced in the build configuration between 0.55 and 0.57 (especially android).

Also it did work with pspdfkit 1.6.1 and 1.7 and RN 0.57.
You can view our old working setup with pspdfkit 1.6.1 and RN 0.57 in [this branch
](https://github.com/leoek/react-native-pspdfkit-demo/tree/pspdfkit-1.6.1)

About the assets and js issues;
I fixed these in both branches, these were the result of the removal of code which was not related to the pdf part of the app.

**Comment by nickwinder** [comment] 2019-01-22 22:58
> Could you look into supporting RN 0.57?

I'll consult with the rest of the team, but as far as I know, there are some blockers currently, as you alluded to I believe Android to be one of them.

> Also it did work with pspdfkit 1.6.1 and 1.7 and RN 0.57.

Interesting, I've always had issues with RN 0.57 and windows.
I'm yet to see the initial issue that you found, as when I tried 0.57 I have incompatibilities with RNFS. Have you seen any issues with this?

**Comment by nickwinder** [comment] 2019-01-25 01:00
I want to keep you in the loop of my advancements on this issue.

It took a while to find a working combination of version. In the end, I did manage to get a working version of the Catalog on https://github.com/PSPDFKit/react-native/pull/162

A retargeting of the Windows version got round the errors you were seeing with `PlatformXmlDir`. But this exposed more issues with 0.57. I found https://github.com/facebook/react-native/issues/21150 which was the issue I was facing and I need to look into more to see what the current state of HEAD is for `react` and `react-native` but version suggestions did work in the end.

I will follow this up with a more concrete PR of which I'll have to pass by the other platform maintainers and possibly create a separate guide for RN 0.57 support for windows.

**Comment by leoek** [comment] 2019-01-26 16:13
Thanks for keeping me in the loop. It's great to hear that you made progress on this!

**Comment by nickwinder** [comment] 2019-02-01 12:45
@leoek I've managed to get the windows SDK reliable and up to date on `react-native` `0.57`, as well as that I've worked with others to ensure all other platforms support `0.57`, so https://github.com/PSPDFKit/react-native/pull/162 has just been merged. 

The issues you were seeing will be resolved now, and the wrapper will be compatible with your application.

**Closed by nickwinder** 2019-02-01 12:45 UTC
Labels: windows
