### ISSUE TITLE
PSPDFKit support for Expo

### ISSUE THREAD

**Issue by visualtechnet** [PSPDFKit/react-native#69] opened 2018-04-11 18:08 UTC
Is there going to be a future to support PSPDFKit for Expo?

https://expo.io/

We have apps that could really use PSPDFKit. If its possible use it without detaching from Expo.

**Comment by radazzouz** [comment] 2018-04-11 18:24
Hi @visualtechnet,

This is a duplicate of issue #25. For more details see the discussion on the issue: https://github.com/PSPDFKit/react-native/issues/25#issuecomment-326215102

Thanks!

**Closed by radazzouz** 2018-04-11 18:24 UTC
Labels: duplicate
